# fly.toml app configuration file generated for eatwhilepregnant on 2024-04-03T20:09:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eatwhilepregnant'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'

[experimental]
  cmd = "start.sh"
  entrypoint = "sh"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "eatwhilepregnant_db"
  destination = "/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
